<?php
/**
 * Created by PhpStorm.
 * User : Leopard
 * Date : 2018/11/20
 * Time : 11:29
 * Email: 417780879@qq.com
 */
namespace app\index\controller;
use app\admin\model\Smess;
use app\common\controller\Base;
use app\common\Predis;
use think\Request;

class Sub extends Base
{
    protected $middleware = ['Hearders'];
    private $config=[
        'length'    =>4,
        //手机验证码地址
        'https'     => 'https://sh2.ipyy.com/sms.aspx',
        'action'    => 'send',
        //用户名
        'userid'    => 'dn44',
        //发送密码
        'password'  => 'dn4455',
        //发送内容
        'content'   => ['上海当日企服提醒：手机号为','的用户提交了需求。【上海当日企服】'],
        'sendTime'  => '',
        'extno'     => ''
    ];
    public function initialize()
    {
        parent ::initialize(); // TODO: Change the autogenerated stub
    }

    /**提交商户,首页需求 sta=0商户，1首页
     * @param Request $request
     *
     * @return \think\response\Json
     */
    public function addsmess(Request $request){
        $data=$request->param();
        $data['cid']=json_encode($data['cid'],JSON_UNESCAPED_UNICODE);
        if(mb_strlen($data['cid'])<5){
            return json(['valid'=>400,'msg'=>'请选择服务项目']);
        }
        $mess=json_decode(Predis::getInstance()->get($data['hearders']['X-Token']),JSON_UNESCAPED_UNICODE);
        $data['phone']=$mess['phone'];
        $res=Smess::create($data)->smid;
        $this->notice();
        return json(['valid'=>200,'msg'=>'提交需求成功']);
    }

    /**
     * 短信通知
     */
    public function notice(){
        $config=$this->config;
        $phone=\app\admin\model\Logos::where('id',1)->value('message');
        $rand = self::UserMess()['phone'];
        $res=file_get_contents($config['https']."?action=".$config['action']."&userid=".$config['userid']."&account=".$config['userid']."&password=".$config['password']."&mobile=" . $phone . "&content=".$config['content'][0] . $rand . $config['content'][1]."&sendTime=".$config['sendTime']."&extno=");
    }

    public function index(Request $request){
        return $request->param('X-Token');
//        dump($this->request->param());
    }
}